import numpy as np

# here are comparing the cosine distance from all the vectors then sorting and then return top5 with their distances also (corrected by ChatGPT)
def getTopKNeighbors(word, W, word2id, id2word, k=5):

    if word not in word2id:
        print("Word not in vocabulary")
        return []

    idx = word2id[word]
    vec = W[idx]

    norm_W = W / np.linalg.norm(W, axis=1, keepdims=True)
    norm_vec = vec / np.linalg.norm(vec)

    sims = np.dot(norm_W, norm_vec)

    sims[idx] = -1.0

    topk_idx = np.argsort(-sims)[:k]

    results = []

    for i in topk_idx:
        results.append((id2word[i], float(sims[i])))

    return results


# Below 2 functions are purely generated by LLM, these were just for illustration, just wanted to see what our model is really predicting
# We need to copy paste these in task_4 specific calls to see the results


# def predictWordNER_Vector(word, embType, d):

#     if embType.lower() == "glove":
#         embeddingPath = f"/kaggle/input/datasets/asmitkr/webinfo/glove_W_{d}.npy"
#         modelPath = f"GloVe-MLP-2Layer_d{d}.pt"
#     else:
#         embeddingPath = f"/kaggle/input/datasets/asmitkr/webinfo/embeddings_{d}.npy"
#         modelPath = f"SVD-MLP-2Layer_d{d}.pt"

#     W = np.load(embeddingPath)

#     with open("/kaggle/input/datasets/asmitkr/webinfo/word2id.pkl", "rb") as f:
#         word2id = pickle.load(f)

#     unkVec = np.mean(W, axis=0)
#     word2id["<UNK>"] = len(word2id)
#     W = np.vstack([W, unkVec])

#     model = NerMLP(d, numLabels)
#     model.load_state_dict(torch.load(modelPath))
#     model.eval()

#     idx = word2id[word] if word in word2id else word2id["<UNK>"]
#     x = torch.tensor(W[idx], dtype=torch.float32).unsqueeze(0)

#     with torch.no_grad():
#         out = model(x)
#         predId = torch.argmax(out, dim=1).item()

#     print("Word:", word)
#     print("Predicted:", nerLabelMap[predId])
#     return nerLabelMap[predId]


# def predictWordNER_Embedding(word, embType, d):

#     if embType.lower() == "glove":
#         embeddingPath = f"/kaggle/input/datasets/asmitkr/webinfo/glove_W_{d}.npy"
#         modelPath = f"GloVe-Embedding_d{d}.pt"
#     else:
#         embeddingPath = f"/kaggle/input/datasets/asmitkr/webinfo/embeddings_{d}.npy"
#         modelPath = f"SVD-Embedding_d{d}.pt"

#     W = np.load(embeddingPath)

#     with open("/kaggle/input/datasets/asmitkr/webinfo/word2id.pkl", "rb") as f:
#         word2id = pickle.load(f)

#     unkVec = np.mean(W, axis=0)
#     word2id["<UNK>"] = len(word2id)
#     W = np.vstack([W, unkVec])

#     model = NerMLP(W, numLabels)
#     model.load_state_dict(torch.load(modelPath))
#     model.eval()

#     idx = word2id[word] if word in word2id else word2id["<UNK>"]
#     x = torch.tensor([idx], dtype=torch.long)

#     with torch.no_grad():
#         out = model(x)
#         predId = torch.argmax(out, dim=1).item()

#     print("Word:", word)
#     print("Predicted:", nerLabelMap[predId])

#     return nerLabelMap[predId]
